apps/usuarios/urls.py
from django.urls import path

from apps.usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.login_propio, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('registrate/', views.registrate, name='registrate'),
    path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate, name='activate'),
]

gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from gym import settings

urlpatterns = [
    path('', include('apps.inicio.urls', namespace='inicio')),
    path('usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    path('alumnos/', include('apps.alumnos.urls', namespace='alumnos')),
    path('api/v1.0/', include('apps.alumnos.routers')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver

SINO = (
    ('S', 'Si'),
    ('N', 'No')
)

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    celular = models.CharField(max_length=100, default='', blank=True)

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Perfil.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.perfil.save()

apps/usuarios/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='Nombre usuario',
                                 widget=forms.TextInput(
                                     attrs={
                                         'class':'form-control input-lg',
                                         'placeholder':'Nombre Usuario'
                                     }
                                 ))
    first_name = forms.CharField(max_length=30, required=False, help_text='Opcional.', label='Nombre',
                                 widget=forms.TextInput(
                                     attrs={
                                         'class':'form-control input-lg',
                                         'placeholder':'Nombre'
                                     }
                                 ))
    last_name = forms.CharField(max_length=30, required=False, help_text='Opcional.', label='Apellido',
                                 widget=forms.TextInput(
                                     attrs={
                                         'class':'form-control input-lg',
                                         'placeholder':'Apellido'
                                     }
                                 ))
    email = forms.EmailField(max_length=254, help_text='Requerido. Informe un correo electronico valido.',
                                 widget=forms.EmailInput(
                                     attrs={
                                         'class':'form-control input-lg',
                                         'placeholder':'Correo electronico'
                                     }
                                 ))
    celular = forms.CharField(max_length=30, required=False, help_text='Opcional.', label='Numero de celular',
                                 widget=forms.TextInput(
                                     attrs={
                                         'class':'form-control input-lg',
                                         'placeholder':'Numero de celular'
                                     }
                                 ))
    password1 = forms.CharField(
        label= "Contraseña",
        strip = False,
        widget = forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class':'form-control input-lg',
            'placeholder':'Contraseña'
        }),
        help_text = password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label = ("Confirmacion Contraseña"),
        widget = forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class':'form-control input-lg',
            'placeholder': 'Repita Contraseña'
        }),
        strip = False,
        help_text = ("Ingrese la misma contraseña para su verficiacion."),
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'celular', 'password1', 'password2', )

apps/usuarios/views.py
# coding=utf-8
from os.path import join

from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login as do_login

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from apps.usuarios.forms import SignUpForm
from apps.usuarios.tokens import account_activation_token


def login_propio(request):
    template = join("default", "usuarios", "login.html")
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                do_login(request, user)
                return redirect('/')
            else:
                messages.error(request, "Contraseña o usuario no valido. Verifique!!!")
        # else:
        #     print('{}'.format(form.errors))

    # Si llegamos al final renderizamos el formulario
    return render(request, template, {'form': form})

def user_logout(request):
    logout(request)
    return redirect('/')

def registrate(request):
    template = join("fasa", "usuarios", "register.html")
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)
            # user.refresh_from_db()  # load the profile instance created by the signal
            user.perfil.celular = form.cleaned_data.get('celular')
            user.save()

            # login(request, user)
            # return redirect('inicio:inicio')
            current_site = get_current_site(request)
            subject = 'Activa tu usuario'
            message = render_to_string('fasa/usuarios/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)

            return redirect('usuarios:account_activation_sent')
    else:
        form = SignUpForm()

    return render(request, template_name=template, context={
        'form':form
    })

def account_activation_sent(request):
    template = join("fasa", "usuarios", "account_activation_sent.html")
    return render(request, template_name=template)


def activate(request, uidb64, token):
    template = join("fasa", "usuarios", "account_activation_invalid.html")
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        # user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('inicio:inicio')
    else:
        return render(request, template_name=template)

templates/default/usuarios/account_activation_email.html
{% autoescape off %}
Hola {{ user.username }},

Por favor hace click en el link de abajo para confirmar tu registracion:

http://{{ domain }}{% url 'usuarios:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/default/usuarios/account_activation_invalid.html
{%extends 'fasa/index.html' %}
{%load static%}
{%block extrahead%}
<link href="{%static 'fasa/css/register.css' %}" rel="stylesheet">
{%endblock%}
{%block content%}
    <div class="container">
        <h3>El link de confirmacion es invalido, puede ser porque ya lo has usado</h3>
    </div>
{%endblock%}

templates/default/usuarios/account_activation_sent.html
{%extends 'fasa/index.html' %}
{%load static%}
{%block extrahead%}
<link href="{%static 'fasa/css/register.css' %}" rel="stylesheet">
{%endblock%}
{%block content%}
    <div class="container">
        <h3>Por favor confirma tu correo electronico para completar la registracion</h3>
    </div>
{%endblock%}

templates/default/usuarios/login.html
{%extends 'default/index.html' %}
{%load static%}
{%block extrahead%}
    <link href="{%static 'default/css/style.css' %}" rel="stylesheet">
{%endblock%}

{%block content%}

<!-- Register Section Begin -->
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="{% get_media_prefix %}imagenes/iconfinder_38_Target_Audience_1688838.png" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form action="#" method="post">
      {% csrf_token %}
      <div class="alert-danger">{{ form.non_field_errors }}</div>

      <div class="form-input">
        <input type="text" id="{{form.username.name}}" class="fadeIn second" name="{{form.username.name}}" placeholder="Usuario">
      </div>
      <div class="form-input">
        <input type="password" id="{{form.pasword.name}}" class="fadeIn third" name="{{form.password.name}}" placeholder="Contraseña">
      </div>
      <div class="form-input">
        <input type="submit" class="fadeIn fourth" value="Ingresar">
      </div>

    </form>
    <div class="contanier">
      <p>Queres tener tu usuario?</p>
      <p>Enviame un <a href="https://wa.me/543743667526?text=Me%20interesa%20el%20acceso%20al%20sistema%20de%20gestion%20de%20gimnasios">WhatsApp <i class="fab fa-whatsapp"></i></a></p>
    </div>


  </div>
</div>
<!-- Register Form Section End -->
{%endblock%}

templates/default/usuarios/register.html
{%extends 'fasa/index.html' %}
{%load static%}
{%block content%}

<div class="container">

<div class="d-flex justify-content-center">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form" method="post">
			{% csrf_token %}
			<h2>Por favor registrate</h2>
			<hr class="colorgraph">
			{% for field in form %}
				<div class="form-group">
<!--						<input type="text" name="display_name" id="display_name" class="form-control input-lg" placeholder="Display Name" tabindex="3">-->
					{{ field }}
					{% if field.help_text %}
          				<small class="form-text text-muted">{{ field.help_text }}</small>
					{% endif %}
					{% for error in field.errors %}
						<div class="invalid-feedback">{{ error }}</div>
        			{% endfor %}
				</div>
			{% endfor %}
			<div class="row">
				 Haciendo click en <strong class="label label-primary">Registar</strong>, ud esta de acuerdo <a href="#" data-toggle="modal" data-target="#t_and_c_m">con los terminos y condiciones</a> impuesto por este sitio, incluyendo el uso de Cookies.
			</div>

			<hr class="colorgraph">
			<div class="row">
				<div class="col-xs-12 col-md-6"><input type="submit" value="Registar" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
				<div class="col-xs-12 col-md-6"><a href="{%url 'usuarios:login' %}" class="btn btn-success btn-block btn-lg">Ingresar</a></div>
			</div>
		</form>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
			</div>
			<div class="modal-body">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>
{%endblock%}
{%block extrajs%}
	<script src="{% static 'fasa/js/register.js' %}"></script>
{%endblock%}