apps/alumnos/urls.py
from os.path import join
from django.urls import path
from django.views.generic import TemplateView

from apps.alumnos import views

app_name = 'alumnos'

urlpatterns = [
    path('', views.listar, name='listar'),
    path('agregar', views.agregar_alumno, name='agregar'),
    path('editar/<int:id>', views.editar_alumno, name='editar'),
    path('borrar/<int:id>', views.borrar_alumno, name='borrar'),
    path('registra_pago/<int:id>', views.registra_pago, name='registra_pago'),
    path('lista_pagos', views.lista_pago, name='lista_pago'),
    path('clases', views.clases, name='clases'),
    path('listar_pagos_alumnos/<int:idalumno>', views.listar_pagos_alumnos, name='listar_pagos_alumnos'),
]

apps/inicio/urls.py
from django.urls import path

from apps.inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
]

apps/usuarios/urls.py
from django.urls import path

from apps.usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.login_propio, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('registrate/', views.registrate, name='registrate'),
    path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate, name='activate'),
]

gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from gym import settings

urlpatterns = [
    path('', include('apps.inicio.urls', namespace='inicio')),
    path('usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    path('alumnos/', include('apps.alumnos.urls', namespace='alumnos')),
    path('api/v1.0/', include('apps.alumnos.routers')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/default/botones.html
{%load static%}
<div class="container">
    <div class="row centered-form center-block">
        <div class="col col-md-3">
            <div class="card">
                <img class="card-img-top" src="{% get_media_prefix%}/imagenes/alumnos.png" alt="Alumnos">
                <div class="card-body">
                    <a href="{%url 'alumnos:listar' %}" class="btn btn-primary col">Alumnos</a>
                </div>
            </div>
        </div>
        <div class="col col-md-3">
            <div class="card">
                <img class="card-img-top" src="{% get_media_prefix%}/imagenes/pagos.png" alt="Pagos">
                <div class="card-body">
                    <a href="{%url 'alumnos:lista_pago' %}" class="btn btn-primary col">Pagos</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/default/footer.html
{%load static%}
<div class="container py-4">
  <div class="container">
    <p><span class="badge badge-info">Tenes alguien para recomendar el sistema?</span></p>
    <p>Enviame un <a href="https://wa.me/543743667526?text=Me%20interesa%20el%20acceso%20al%20sistema%20de%20gestion%20de%20gimnasios">WhatsApp <i class="fab fa-whatsapp"></i></a></p>
  </div>
  <div class="copyright">
    &copy; Copyright <strong><span><a href="http://www.servinlgsm.com.ar"> Servin</a></span></strong>
  </div>
  <div class="credits">
    <!-- All the links in the footer should remain intact. -->
    <!-- You can delete the links only if you purchased the pro version. -->
    <!-- Licensing information: https://bootstrapmade.com/license/ -->
    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-app-landing-page-template/ -->
    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
  </div>
</div>

templates/default/index.html
{% load static %}
{% load i18n static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Gestion - Gym :: {%block title%}Inicio{%endblock%}</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{%get_media_prefix%}/imagenes/logo_s.png" rel="icon">
  <link href="{%get_media_prefix%}/imagenes/logo_s.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  
  <!-- Vendor CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="{%static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{%static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{%static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{%static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{%static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{%static 'default/css/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{%static 'assets/css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  {%block extrahead%}
  {%endblock%}
  <!-- =======================================================
  * Template Name: Appland - v2.2.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-app-landing-page-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top  header-transparent ">
    {%if user.is_authenticated%}
      {%include 'default/navbar.html' %}
    {%endif%}
  </header><!-- End Header -->

  <main id="main">
    {%block content%}
    {%if user.is_authenticated%}
      {%include 'default/botones.html'%}
    {%endif%}
    {%endblock%}
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="">
      {%if user.is_authenticated%}
        {%include 'default/footer.html'%}
      {%endif%}
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{%static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <script src="{%static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{%static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{%static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{%static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{%static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{%static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{%static 'assets/js/main.js' %}"></script>

</body>
<!-- vue.js files -->
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.5"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
$.datepicker.regional['es'] = {
     closeText: 'Cerrar',
     prevText: '< Ant',
     nextText: 'Sig >',
     currentText: 'Hoy',
     monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
     monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
     dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
     dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
     dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
     weekHeader: 'Sm',
     dateFormat: 'dd/mm/yy',
     firstDay: 1,
     isRTL: false,
     showMonthAfterYear: false,
     yearSuffix: ''
     };
     $.datepicker.setDefaults($.datepicker.regional['es']);
    $(function(){
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            showOtherMonths: true,
            selectOtherMonths: true,
            changeMonth: true,
            changeYear: true,
        });
    });
</script>
{%block extrajs%}
{%endblock%}
</html>

templates/default/navbar.html
{%load static%}
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{%url 'inicio:inicio' %}">Gestion-Gym {{request.user}}</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="{%url 'inicio:inicio' %}">Inicio</a></li>
          <li><a href="{%url 'alumnos:listar' %}">Alumnos</a></li>
          <li><a href="{%url 'alumnos:lista_pago' %}">Cobranzas</a></li>
          <li><a href="{%url 'alumnos:clases' %}">Clases</a></li>
          <li><a href="#contact">Contactate</a></li>
          <li><a href="{%url 'usuarios:logout' %}">Cerrar Sesion</a></li>
        </ul>
      </nav><!-- .nav-menu -->

    </div>

templates/default/paginador.html
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">

            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" href="?page=1" tabindex="-1"><i class="fas fa-step-backward"></i></a>
            </li>
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %} " tabindex="-1"><i class="fas fa-backward"></i></a>
            </li>

            {% if page_obj.number|add:'-2' > 1 %}
                <li class="page-item disabled"><a class="page-link" href="?page={{ page_obj.number|add:'-3' }}">&hellip;</a></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item disabled"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.paginator.num_pages > page_obj.number|add:'3' %}
                <li class="page-item disabled"><a class="page-link" href="?page={{ page_obj.number|add:'3' }}">&hellip;</a></li>
            {% endif %}

            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% endif %}"><i class="fas fa-forward"></i></a>
            </li>
            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %} ?page={{ page_obj.paginator.num_pages }}  {% endif %}"><i class="fas fa-step-forward"></i></a>
            </li>
        </ul>
    </nav>