apps/alumnos/urls.py
from os.path import join
from django.urls import path
from django.views.generic import TemplateView

from apps.alumnos import views

app_name = 'alumnos'

urlpatterns = [
    path('', views.listar, name='listar'),
    path('agregar', views.agregar_alumno, name='agregar'),
    path('editar/<int:id>', views.editar_alumno, name='editar'),
    path('borrar/<int:id>', views.borrar_alumno, name='borrar'),
    path('registra_pago/<int:id>', views.registra_pago, name='registra_pago'),
    path('lista_pagos', views.lista_pago, name='lista_pago'),
    path('clases', views.clases, name='clases'),
    path('listar_pagos_alumnos/<int:idalumno>', views.listar_pagos_alumnos, name='listar_pagos_alumnos'),
]

gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from gym import settings

urlpatterns = [
    path('', include('apps.inicio.urls', namespace='inicio')),
    path('usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    path('alumnos/', include('apps.alumnos.urls', namespace='alumnos')),
    path('api/v1.0/', include('apps.alumnos.routers')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/alumnos/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Clases(models.Model):
    nombre = models.CharField(max_length=80, default='')
    monto = models.DecimalField(max_digits=12, decimal_places=2)
    empresa = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)

    class Meta:
        ordering = ['nombre']
        verbose_name = 'Clase'
        verbose_name_plural = 'Clases'

    def __str__(self):
        return self.nombre

class Alumno(models.Model):

    nombre = models.CharField(max_length=50, default='')
    celular = models.CharField(max_length=50, default='', blank=True)
    email = models.EmailField(max_length=150, default='', blank=True)
    empresa = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    fecha_nacimiento = models.DateField(default=datetime.now().date())
    clases = models.ManyToManyField(Clases, default=1)

    def __str__(self):
        return self.nombre


class Pagos(models.Model):

    alumno = models.ForeignKey(Alumno, on_delete=models.DO_NOTHING)
    fecha = models.DateField(default=datetime.now().date())
    monto = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    comentario = models.CharField(max_length=150, default='')

apps/alumnos/forms.py
from datetime import datetime

from django import forms

from apps.alumnos.models import Alumno, Pagos


class AlumnoForm(forms.ModelForm):

    class Meta:
        model = Alumno
        exclude = ['id','empresa']
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={
                'class':'form-control datepicker',
            })
        }
        labels = {
            "fecha_nacimiento": "Fecha de ingreso"
        }

class PagoForm(forms.ModelForm):

    class Meta:
        model = Pagos
        exclude = ['id', 'alumno']

class BusquedaAlumnoForm(forms.Form):
    nombre = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder':'Busqueda'
        }
    ))

class DesdeHastaFecha(forms.Form):
    # desde = forms.DateField(initial=datetime.now().date())
    # hasta = forms.DateField(initial=datetime.now().date())
    desde = forms.DateField(widget=forms.DateInput(format=('%d/%m/%Y'),
        attrs={'class':'form-control datepicker',}
    ), initial=datetime.now().date())
    hasta = forms.DateField(widget=forms.DateInput(format=('%d/%m/%Y'),
        attrs={'class':'form-control datepicker', }
    ), initial=datetime.now().date())

apps/alumnos/views.py
from os.path import join

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from apps.alumnos.forms import AlumnoForm, PagoForm, BusquedaAlumnoForm, DesdeHastaFecha
from apps.alumnos.models import Alumno, Pagos, Clases


@login_required(login_url='usuarios:login')
def listar(request):
    template = join('default', 'alumnos', 'listar.html')
    page = request.GET.get('page', 1)

    form = BusquedaAlumnoForm()
    alumnos_list = Alumno.objects.filter(empresa=request.user)
    if request.method == 'POST':
        form = BusquedaAlumnoForm(request.POST)
        if form.is_valid():
            alumnos_list = alumnos_list.filter(nombre__icontains = form.cleaned_data.get('nombre'))

    paginator = Paginator(alumnos_list, 12)
    try:
        alumnos = paginator.page(page)
    except PageNotAnInteger:
        alumnos = paginator.page(1)
    except EmptyPage:
        alumnos = paginator.page(paginator.num_pages)

    return render(request, template, context={
        'alumnos': alumnos,
        'form': form,
    })

@login_required(login_url='usuarios:login')
def agregar_alumno(request):
    template = join('default', 'alumnos', 'alumno.html')
    if request.method == 'POST':
        form = AlumnoForm(request.POST)
        if form.is_valid():
            nuevo_alumno = form.save(commit=False)
            nuevo_alumno.empresa = request.user
            nuevo_alumno.save()
            return HttpResponseRedirect(reverse('alumnos:listar'))
    else:
        form = AlumnoForm()
        form.fields['clases'].queryset = Clases.objects.filter(empresa=request.user)

    return render(request, template, context={
        'form': form
    })

@login_required(login_url='usuarios:login')
def editar_alumno(request, id=1):
    template = join('default', 'alumnos', 'alumno.html')
    nombre_boton = 'Modificar Alumno'
    form = None
    alumno = None

    if request.method == 'POST':
        form = AlumnoForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            alumno = Alumno.objects.get(id=id, empresa=request.user)
            alumno.nombre = cd['nombre']
            alumno.celular = cd['celular']
            alumno.email = cd['email']
            alumno.fecha_nacimiento = cd['fecha_nacimiento']
            alumno.clases.set(cd['clases'])
            alumno.save()
            return HttpResponseRedirect(reverse('alumnos:listar'))
    else:
        try:
            alumno = Alumno.objects.get(id=id)
            form = AlumnoForm(initial={
                'nombre':alumno.nombre,
                'celular':alumno.celular,
                'email':alumno.email,
                'fecha_nacimiento':alumno.fecha_nacimiento,
                'clases':[c.id for c in alumno.clases.all()]
            })
            form.fields['clases'].queryset = Clases.objects.filter(empresa=request.user)

        except:
            form = None
            alumno = None

    return render(request, template, context={
        'form': form,
        'nombre_boton': nombre_boton
    })

@login_required(login_url='usuarios:login')
def borrar_alumno(request, id=1):
    template = join('default', 'alumnos', 'alumno.html')
    nombre_boton = 'Eliminar Alumno'
    form = None
    alumno = None

    if request.method == 'POST':
        form = AlumnoForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            alumno = Alumno.objects.get(id=id, empresa=request.user)
            alumno.delete()
            return HttpResponseRedirect(reverse('alumnos:listar'))
    else:
        try:
            alumno = Alumno.objects.get(id=id)
            form = AlumnoForm(initial={
                'nombre': alumno.nombre,
                'celular': alumno.celular,
                'email': alumno.email,
                'fecha_nacimiento': alumno.fecha_nacimiento
            })
            print(alumno)
        except:
            form = None
            alumno = None

    return render(request, template, context={
        'form': form,
        'nombre_boton': nombre_boton
    })

@login_required(login_url='usuarios:login')
def registra_pago(request, id=1):

    template = join('default', 'alumnos', 'pagos.html')
    try:
        pagos = Pagos.objects.filter(alumno = id, alumno__empresa = request.user).order_by('-id')[0]
        ultimo_pago = pagos.monto
    except:
        ultimo_pago = 0

    form = PagoForm(initial={
        'monto':ultimo_pago
    })
    alumno = Alumno.objects.get(id=id)
    if request.method == 'POST':
        form = PagoForm(request.POST)
        if form.is_valid():
            pago = form.save(commit=False)
            pago.alumno = alumno
            pago.save()
            return HttpResponseRedirect(reverse('alumnos:listar'))

    return render(request, template, context={
        'form':form,
        'alumno':alumno
    })

@login_required(login_url='usuarios:login')
def lista_pago(request):
    template = join('default', 'alumnos', 'lista_pagos.html')
    form = DesdeHastaFecha()
    pagos = None
    if request.method == 'POST':
        form = DesdeHastaFecha(request.POST)
        if form.is_valid():
            pagos = Pagos.objects.filter(
                fecha__gte = form.cleaned_data.get('desde'),
                fecha__lte = form.cleaned_data.get('hasta'),
                alumno__empresa = request.user
            )
    return render(request, template, context={
        'form': form,
        'pagos': pagos
    })

@login_required(login_url='usuarios:login')
def clases(request):
    template = join('default', 'alumnos', 'clases.html')
    #hago toda la logica en el html con vue js
    return render(request, template)

@login_required(login_url='usuarios:login')
def listar_pagos_alumnos(request, idalumno=0):
    template = join('default', 'alumnos', 'lista_pagos.html')
    form = DesdeHastaFecha()
    pagos = None
    if request.method == 'POST':
        form = DesdeHastaFecha(request.POST)
        if form.is_valid():
            pagos = Pagos.objects.filter(
                fecha__gte = form.cleaned_data.get('desde'),
                fecha__lte = form.cleaned_data.get('hasta'),
                alumno__empresa = request.user,
                alumno__id = idalumno,
            )
    return render(request, template, context={
        'form': form,
        'pagos': pagos
    })

templates/default/alumnos/alumno.html
{%extends 'default/index.html' %}
{%load static%}
{%block title%}
    Alumnos
{%endblock%}

{%block content%}
<div class="container">
    {%if nombre_boton%}
        <h3>{{nombre_boton}}</h3>
    {%else%}
        <h3>Añadir Alumno</h3>
    {%endif%}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {%if nombre_boton%}
            <input type="submit" value="{{nombre_boton}}" />
        {%else%}
            <input type="submit" value="Añadir alumno" />
        {%endif%}
    </form>
</div>
{%endblock%}

templates/default/alumnos/clases.html
{%extends 'default/index.html' %}
{%load static%}
{%block title%}
    Clases
{%endblock%}

{%block content%}
<div id="clases">
    <div class="container">
        <h1>Lista de clases</h1>
        <div class="row">
            <button  type="button" class="btn btn-primary col" data-toggle="modal" data-target="#addClaseModal"><i class="far fa-plus-square"></i></button>
            <input class="form-control mr-sm-2 col-8" type="text" placeholder="Busqueda" v-model="search_term" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 col" v-on:click.prevent="getClases()"><i class="fas fa-search"></i></button>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Accion</th>
            </tr>
            </thead>
            <tbody>
                <tr v-for="clase in clases">
                    <th scope="row">${clase.id}$</th>
                    <td>${clase.nombre}$</td>
                    <td>
                      <button class="btn btn-info" v-on:click="getClase(clase.id)"><i class="far fa-edit"></i></button>
                      <button class="btn btn-danger" v-on:click="deleteClase(clase.id)"><i class="far fa-trash-alt"></i></button>
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- Add clase Modal -->
          <div class="modal fade" id="addClaseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Agregar Clase</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form v-on:submit.prevent="addClase()">
                    <div class="modal-body">
                        <div class="form-group">
                          <label for="clase_nombre">Nombre Clase</label>
                          <input
                            type="text"
                            class="form-control"
                            id="clase_nombre"
                            placeholder="Ingrese el nombre de la clase"
                            v-model="newClase.nombre"
                            required="required" >
                        </div>
                        <div class="form-group">
                          <label for="clase_monto">Monto</label>
                          <input type="number"
                            class="form-control"
                            id="clase_monto"
                            placeholder="Ingrese el monto"
                            v-model="newClase.monto"
                            required="required">
                        </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary m-progress" data-dismiss="modal">Cerrar</button>
                      <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
              </div>
            </div>
            <div class="loading" v-if="loading===true">Cargando&#8230;</div>
          </div>
          <!-- End of add article modal -->
        <!-- Edit clase Modal -->
          <div class="modal fade" id="editClaseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" >Editar Clase</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form v-on:submit.prevent="editClase()">
                    <div class="modal-body">
                        <div class="form-group">
                          <label for="edit_clase_nombre">Nombre Clase</label>
                          <input
                            type="text"
                            class="form-control"
                            id="edit_clase_nombre"
                            placeholder="Ingrese el nombre de la clase"
                            v-model="currentClase.nombre"
                            required="required" >
                        </div>
                        <div class="form-group">
                          <label for="edit_clase_monto">Monto</label>
                          <input type="number"
                            class="form-control"
                            id="edit_clase_monto"
                            placeholder="Ingrese el monto"
                            v-model="currentClase.monto"
                            required="required">
                        </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary m-progress" data-dismiss="modal">Cerrar</button>
                      <button type="submit" class="btn btn-primary" >Guardar</button>
                    </div>
                </form>
              </div>
            </div>
            <div class="loading" v-if="loading===true">Cargando&#8230;</div>
          </div>
          <!-- End of edit article modal -->
    </div>
</div>
{%endblock%}

{%block extrajs%}

<script type="text/javascript">
    function readCookie(name) {
        var nameEQ = name + "=";
        var ca = document.cookie.split(';');
        for(var i=0;i < ca.length;i++) {
            var c = ca[i];
            while (c.charAt(0)==' ') c = c.substring(1,c.length);
                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
        }
        return null;
    }
    var csrftoken = readCookie('csrftoken');
    new Vue({
       el: '#clases',
       delimiters: ['${','}$'],
       data: {
            clases: [],
            loading: false,
            currentClase: {},
            message: null,
            newClase: { 'nombre': null, 'monto': null, 'empresa': {{request.user.id}} },
            search_term: '',
            csrftoken: csrftoken,
        },
         mounted: function() {
            this.getClases();
         },
     methods: {
        getClases: function(){
            let api_url = '/api/v1.0/clases';
            if(this.search_term!==''||this.search_term!==null) {
                api_url = '/api/v1.0/clases/?search='+this.search_term
          }
          this.loading = true;
          this.$http.get(api_url)
              .then((response) => {
                this.clases = response.data;
                this.loading = false;
                console.log(this.clases);
              })
              .catch((err) => {
                this.loading = false;
                console.log(err);
           })
        },
        getClase: function(id) {
          this.loading = true;
          console.log("ID Buscado => " + id);
          this.$http.get('/api/v1.0/clases/'+id+'/')
              .then((response) => {
                this.currentClase = response.data;
                $("#editClaseModal").modal('show');
                this.loading = false;
              })
              .catch((err) => {
                this.loading = false;
                console.log(err);
              })
        },
        addClase: function() {
          this.loading = true;
          console.log(this.csrftoken);
          this.$http.post('/api/v1.0/clases/',this.newClase,{headers: {"X-CSRFToken":this.csrftoken}})
              .then((response) => {
                this.loading = true;
                this.getClases();
                $('#addClaseModal').modal('hide')
              })
              .catch((err) => {
                this.loading = true;
                console.log(err);
              })
        },
        editClase: function() {
          this.loading = true;
          console.log(this.currentClase);
          this.$http.put('/api/v1.0/clases/'+this.currentClase.id+'/', this.currentClase, {headers: {"X-CSRFToken":this.csrftoken}})
              .then((response) => {
                this.loading = false;
                this.currentClase = response.data;
                this.getClases();
                $('#editClaseModal').modal('hide')
              })
              .catch((err) => {
                this.loading = false;
                console.log(err);
              })
        },
        deleteClase: function(id) {
          this.loading = true;
            swal({
              title: "Esta seguro?",
              text: "Una vez eliminado no es posible recuperar rel registro!",
              icon: "warning",
              buttons: true,
              dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                  this.$http.delete('/api/v1.0/clases/'+id+'/',{headers: {"X-CSRFToken":this.csrftoken}})
                      .then((response) => {
                        this.loading = false;
                        this.getClases();
                      })
                      .catch((err) => {
                        this.loading = false;
                        console.log(err);
                      })
              } else {
                swal("El registro no ha sido eliminado!");
              }
            });
        }
    },
  });
</script>
{%endblock%}

templates/default/alumnos/lista_pagos.html
{%extends 'default/index.html' %}
{%load static%}
{%block title%}
    Lista pagos
{%endblock%}

{%block content%}
<div class="container" id="pagos">
    <h3>Lista pago</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Listar" />
    </form>
    <div class="row">
        <table class="table table-striped custab">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Alumno</th>
                    <th>Monto</th>
                    <th>Accion</th>
                </tr>
            </thead>
            <tbody>
                {%for p in pagos%}
                    <tr>
                        <td>{{p.fecha}}</td>
                        <td>{{p.alumno}}</td>
                        <td>{{p.monto}}</td>
                        <td><button class="btn btn-danger" v-on:click="deletePago({{p.id}})"><i class="far fa-trash-alt"></i></button></td>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</div>
{%endblock%}

{%block extrajs%}
<script type="text/javascript">
    function readCookie(name) {
        var nameEQ = name + "=";
        var ca = document.cookie.split(';');
        for(var i=0;i < ca.length;i++) {
            var c = ca[i];
            while (c.charAt(0)==' ') c = c.substring(1,c.length);
                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
        }
        return null;
    }
    var csrftoken = readCookie('csrftoken');
    new Vue({
       el: '#pagos',
       delimiters: ['${','}$'],
       data: {
            pagos: [],
            currentPago: {},
            message: null,
            csrftoken: csrftoken,
        },
        methods: {
            deletePago: function(id) {
                console.log("id a borrar => " + id);
                swal({
                  title: "Esta seguro?",
                  text: "Una vez eliminado no es posible recuperar rel registro!",
                  icon: "warning",
                  buttons: true,
                  dangerMode: true,
                })
                .then((willDelete) => {
                  if (willDelete) {
                      this.$http.delete('/api/v1.0/pagos/'+id+'/',{headers: {"X-CSRFToken":this.csrftoken}})
                          .then((response) => {
                            this.loading = false;
                          })
                          .catch((err) => {
                            this.loading = false;
                            console.log(err);
                          })
                  } else {
                    swal("El registro no ha sido eliminado!");
                  }
                });
            }
        }
   });
</script>

{%endblock%}

templates/default/alumnos/listar.html
{%extends 'default/index.html' %}
{%load static%}
{%block extrahead%}
    <link href="{%static 'default/css/alumnos.css' %}" rel="stylesheet">
{%endblock%}

{%block content%}
<div class="container">
    <h3>Alumnos</h3>
    <div class="row">
        <form method="post" class="form-inline">
            {% csrf_token %}
<!--            <div class="col col-md-12 col-xs-12 col-sm">-->
            <div class="form-group mb-2">
                {{form.nombre}}
            </div>
            <div class="form-group mb-2">
                <button type="submit" class="btn btn-primary"><i class="fas fa-search-plus"></i></button>
            </div>
        </form>
<!--            </div>-->
    </div>

    <div class="row">
        <table class="table table-striped custab">
        <div class="col">
            <a href="{%url 'alumnos:agregar' %}" class="btn btn-primary btn-xs pull-right"><i class="fas fa-user-plus"></i></a>
        </div>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th class="text-center">Accion</th>
            </tr>
            </thead>
            <tbody>
            {%for a in alumnos%}
                <tr>
                    <td>{{a.id}}</td>
                    <td>{{a.nombre}}</td>
                    <td class="text-center">
                        <a class='btn btn-info btn-xs' href="{%url 'alumnos:editar' a.id %}"><i class="fas fa-user-edit"></i></a>
                        <a href="{%url 'alumnos:registra_pago' a.id %}" class="btn btn-success btn-xs"><i class="far fa-money-bill-alt"></i></a>
                        <a href="{%url 'alumnos:borrar' a.id %}" class="btn btn-danger btn-xs"><i class="fas fa-user-minus"></i></a>
                        <a href="{%url 'alumnos:listar_pagos_alumnos' idalumno=a.id %}" class="btn btn-info btn-xs"><i class="fas fa-hand-holding-usd"></i></a>
                    </td>
                </tr>
            {%endfor%}
            </tbody>
        </table>
        {%include 'default/paginador.html' with page_obj=alumnos%}
    </div>
</div>
{%endblock%}

templates/default/alumnos/pagos.html
{%extends 'default/index.html' %}
{%load static%}
{%block title%}
    Registra pagos
{%endblock%}

{%block content%}
<div class="container">
    <h3>Registra pago</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Registrar" />
    </form>
    <h5>Clases activas</h5>
    <div class="row">
        {%for clase in alumno.clases.all%}
            <p class="text-justify">{{clase.nombre}} - ${{clase.monto}}</p>
        {%endfor%}
    </div>
</div>
{%endblock%}